services:
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - project-compose-network

  busybox:
    image: busybox:latest
    command: sh -c "echo 'busybox ready' && sleep 3600"
    networks:
      - project-compose-network

networks:
  project-compose-network:
    external: true
