package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"raioz/internal/config"
	"raioz/internal/detect"
	"raioz/internal/output"

	"gopkg.in/yaml.v3"
)

// InitScanOptions contains options for the init scan use case.
type InitScanOptions struct {
	Dir        string
	OutputPath string
	Project    string
}

// InitScanUseCase handles auto-scanning a directory to generate raioz.yaml.
type InitScanUseCase struct{}

// NewInitScanUseCase creates a new InitScanUseCase.
func NewInitScanUseCase() *InitScanUseCase {
	return &InitScanUseCase{}
}

// Execute scans the directory and generates a raioz.yaml.
func (uc *InitScanUseCase) Execute(opts InitScanOptions) error {
	dir := opts.Dir
	if dir == "" {
		var err error
		dir, err = os.Getwd()
		if err != nil {
			return fmt.Errorf("get working directory: %w", err)
		}
	}

	projectName := opts.Project
	if projectName == "" {
		projectName = filepath.Base(dir)
	}

	output.PrintInfo(fmt.Sprintf("Scanning %s...", dir))
	fmt.Println()

	cfg := config.RaiozConfig{
		Project:  projectName,
		Services: make(map[string]config.YAMLService),
		Deps:     make(map[string]config.YAMLDependency),
	}

	// Phase 1: Detect services from subdirectories
	output.PrintSubsection("Services detected")
	uc.scanServices(dir, &cfg)

	// Check root directory if no subdirectory services found
	if len(cfg.Services) == 0 {
		rootResult := detect.Detect(dir)
		if rootResult.Runtime != detect.RuntimeUnknown {
			svc := buildServiceFromDetection(projectName, ".", rootResult)
			cfg.Services[projectName] = svc
			output.PrintInfo(fmt.Sprintf("  . → %s (%s)", rootResult.Runtime, rootResult.StartCommand))
		}
	}

	// Phase 2: Infer dependencies from .env files
	output.PrintSubsection("Dependencies inferred")
	inferredDeps, inferredLinks := detect.InferDepsFromEnv(dir)

	for _, dep := range inferredDeps {
		if _, exists := cfg.Deps[dep.Name]; exists {
			continue
		}
		yamlDep := config.YAMLDependency{
			Image: dep.Image,
			Ports: config.YAMLStringSlice{dep.Port},
		}
		// Auto-detect .env.{name} file (e.g., .env.postgres)
		envFile := ".env." + dep.Name
		if _, err := os.Stat(filepath.Join(dir, envFile)); err == nil {
			yamlDep.Env = config.YAMLStringSlice{envFile}
		}
		cfg.Deps[dep.Name] = yamlDep
		output.PrintInfo(fmt.Sprintf("  %s → %s (from %s)", dep.Name, dep.Image, dep.Source))
	}

	// Phase 3: Check for docker-compose.yml in root (extract infra services)
	uc.scanRootCompose(dir, &cfg)

	// Phase 4: Wire dependsOn from inferred links
	for _, link := range inferredLinks {
		if svc, ok := cfg.Services[link.From]; ok {
			if !contains(svc.DependsOn, link.To) {
				svc.DependsOn = append(svc.DependsOn, link.To)
				cfg.Services[link.From] = svc
			}
		}
	}

	// Show dependency links
	if len(inferredLinks) > 0 {
		fmt.Println()
		output.PrintSubsection("Dependency links")
		seen := make(map[string]bool)
		for _, link := range inferredLinks {
			key := link.From + "→" + link.To
			if !seen[key] {
				seen[key] = true
				output.PrintInfo(fmt.Sprintf("  %s → %s", link.From, link.To))
			}
		}
	}

	if len(cfg.Services) == 0 && len(cfg.Deps) == 0 {
		output.PrintWarning("No services or dependencies detected. Create raioz.yaml manually.")
		return nil
	}

	// Write YAML
	fmt.Println()
	outPath := opts.OutputPath
	if outPath == "" {
		outPath = filepath.Join(dir, "raioz.yaml")
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	// Add a header comment
	header := "# Generated by raioz init — edit as needed\n"
	data = append([]byte(header), data...)

	if err := os.WriteFile(outPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", outPath, err)
	}

	output.PrintSuccess(fmt.Sprintf(
		"Generated %s with %d services and %d dependencies",
		outPath, len(cfg.Services), len(cfg.Deps),
	))
	return nil
}

// scanServices scans subdirectories for service projects.
func (uc *InitScanUseCase) scanServices(dir string, cfg *config.RaiozConfig) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || isIgnoredDir(entry.Name()) {
			continue
		}

		subPath := filepath.Join(dir, entry.Name())
		result := detect.Detect(subPath)

		if result.Runtime == detect.RuntimeUnknown {
			continue
		}

		name := entry.Name()
		svc := buildServiceFromDetection(name, "./"+name, result)
		cfg.Services[name] = svc

		output.PrintInfo(fmt.Sprintf("  %s → %s (%s)", name, result.Runtime, result.StartCommand))
	}
}

// scanRootCompose checks for docker-compose.yml in the root and extracts infra.
func (uc *InitScanUseCase) scanRootCompose(dir string, cfg *config.RaiozConfig) {
	composeNames := []string{"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml"}
	for _, name := range composeNames {
		composePath := filepath.Join(dir, name)
		if _, err := os.Stat(composePath); err != nil {
			continue
		}

		composeDeps := detect.InferDepsFromCompose(composePath)
		for _, dep := range composeDeps {
			if _, exists := cfg.Deps[dep.Name]; exists {
				continue
			}
			cfg.Deps[dep.Name] = config.YAMLDependency{
				Image: dep.Image,
				Ports: config.YAMLStringSlice{dep.Port},
			}
			output.PrintInfo(fmt.Sprintf("  %s → %s (from %s)", dep.Name, dep.Image, dep.Source))
		}
		break // Only process the first compose found
	}
}

func buildServiceFromDetection(_, path string, result detect.DetectResult) config.YAMLService {
	svc := config.YAMLService{
		Path: path,
	}
	if result.Port > 0 {
		svc.Ports = config.YAMLStringSlice{fmt.Sprintf("%d", result.Port)}
	}
	if result.HasHotReload {
		svc.Watch = config.YAMLWatch{Enabled: true, Mode: "native"}
	}
	return svc
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

var ignoredDirs = map[string]bool{
	"node_modules": true, "vendor": true, ".git": true,
	"dist": true, "build": true, ".next": true, ".nuxt": true,
	"target": true, "bin": true, "__pycache__": true,
	"examples": true, "docs": true, "scripts": true,
	"infra": false, // scan infra dirs for compose files
}

func isIgnoredDir(name string) bool {
	return ignoredDirs[name]
}
